#!/usr/bin/env python3

import json
import pathlib
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate_collection.py <source-json> <dest-go>", file=sys.stderr)
        return 2

    source_path = pathlib.Path(sys.argv[1])
    dest_path = pathlib.Path(sys.argv[2])

    raw = source_path.read_text(encoding="utf-8")
    parsed = json.loads(raw)

    if isinstance(parsed, dict) and isinstance(parsed.get("collection"), dict):
        parsed = parsed["collection"]

    minified = json.dumps(parsed, separators=(",", ":"), ensure_ascii=False)
    generated = (
        "// Code generated by make collection-generate; DO NOT EDIT.\n"
        "package postman\n\n"
        "func init() {\n"
        f"\tgeneratedCollectionJSON = {json.dumps(minified, ensure_ascii=False)}\n"
        "}\n"
    )

    dest_path.parent.mkdir(parents=True, exist_ok=True)
    dest_path.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
